apiVersion: v1
kind: Service
metadata:
  name: tupan-web
  namespace: tupan
  labels:
    app: tupan-web
spec:
  type: ClusterIP
  selector:
    app: tupan-web
  ports:
    - name: http
      port: 80
      targetPort: 5000
